name: Build and deploy ASP app to Azure Web App - MyMvcAppHackathonChallenge

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and publish
        run: dotnet publish -c Release -o ./bin/Release/net8.0/MyMvcAppHackathonChallenge

      - name: Verify publish directory
        run: dir ./bin/Release/net8.0/MyMvcAppHackathonChallenge

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ./bin/Release/net8.0/MyMvcAppHackathonChallenge

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E23273EB150B4B5087F4FAF337189948 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8986C7C41CD041EF9B72111443159F12 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6FFDEAFC6013493686B67D4A69226495 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MyMvcAppHackathonChallenge'
          slot-name: 'Production'
          package: ./bin/Release/net8.0/MyMvcAppHackathonChallenge
